/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://nuj7hxgsxzdejlcau2ty6akkjy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kzjbax2wnrdppa4yx72dip7x6y",
    "aws_cognito_identity_pool_id": "us-west-2:fd345bcf-99c2-4dcc-9b96-c28fb474ae4a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3NGuHWkLd",
    "aws_user_pools_web_client_id": "20kbe6anlu3js5sk1u4kaoh8bq",
    "oauth": {
        "domain": "commhub8d74ff2e-8d74ff2e-prod.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "dap://",
        "redirectSignOut": "dap://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "commhubimages24e37-prod",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
